version: '3.8'

services:
  #backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "80:80"  # Mapear a porta 80 do contêiner para 8000 no host
    networks:
      - backend-network
    depends_on:
      - db

  #client
  client:
    build:
      context: ./frontend-hub
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-hub:/app
    environment:
      NODE_ENV: development
    command: [ "npx", "nx", "dev", "client", "--port=3000" ]
    extra_hosts:
      - api.backend.local:172.20.0.5
    networks:
      - backend-network
    #client
  admin:
    build:
      context: ./frontend-hub
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "3001:3001"
    volumes:
      - ./frontend-hub:/app
    environment:
      NODE_ENV: development
    command: [ "npx", "nx", "dev", "admin", "--port=3001" ]
    extra_hosts:
      - api.backend.local:172.20.0.5
    networks:
      - backend-network

  #nginx
  # nginx:
  #   image: nginx:latest
  #   container_name: Nginx
  #   volumes:
  #     - ./backend:/var/www/html
  #     - ./frontend-hub:/app
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8000:80"
  #   networks:
  #     - backend-network
  #   depends_on:
  #     - backend

  # db database
  db:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: babbo
      MYSQL_USER: root
      MYSQL_PASSWORD: developer
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
